name: 'add-code-reviewers'
description: 'Action to add reviews to a pull request'
author: 'Alex Parra'

runs:
  using: node20
  main: 'dist/index.js'

inputs:
  github_token:
    description: 'GitHub token'
    required: false
  reviewers_file_path:
    description: 'Reviewers file'
    default: '.bakery/reviewers.yml'
    required: true

outputs:
  reviewers:
    description: 'Reviewers added to the pull request'

branding:
  icon: 'thumbs-up'
  color: 'blue'